### ISSUE TITLE
This https://docs.expressionengine.com/v6/installation/update.html link is not working which coming in the upgrade from EE6 beta 4 to RC.

### ISSUE THREAD

**Issue by Bhavin9898** [ExpressionEngine/ExpressionEngine-User-Guide#114]
![image](https://user-images.githubusercontent.com/16367350/101891809-8b35f800-3bc8-11eb-8236-6a90302bbac0.png)

**Comment by intoeetive** [comment]
@ops-andy looks like we have redirect rule set up for `v5/installation/update.html` and `latest/installation/update.html` but not for `v6/installation/update.html`

**Comment by ops-andy** [comment]
redirect added
