### ISSUE TITLE
Issue creating when upgrading from EE6 beta 4 to RC1? How Can I solve it?

### ISSUE THREAD

**Issue by Bhavin9898** [ExpressionEngine/ExpressionEngine-User-Guide#115]
Below step to create the error.

1. Upgrade ee6 beta 4 to RC1 using the one click button.
2. Upgrade is not completed due some error show in the view trace.
3. Refresh the page and go back the delete upgrade class in EE folder.
4. Then I got below error on every page page.
![image](https://user-images.githubusercontent.com/16367350/101911026-cf83c100-3be5-11eb-82cd-6a9bdbf27d56.png)

Can you tell me how can I solve it?

Thanks

**Comment by ops-andy** [comment]
this seems like it was a support request not an issue with the docs. Please keep issues here related to the documentation only.
thanks
