### ISSUE TITLE
File entries tags (caption vs description)

### ISSUE THREAD

**Issue by Yvan256** [ExpressionEngine/ExpressionEngine-User-Guide#13]
https://docs.expressionengine.com/latest/add-ons/file/file_tag.html

The variable "caption" is used twice on the page but it's not in the list of variables. It seems to be an alias for "description" (or the other way around). A small note about this would be helpful.

**Comment by garethtdavies** [comment]
See this: https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/EllisLab/Addons/file/mod.file.php#L448. The examples should just be updated caption->description.
