### ISSUE TITLE
Example text wrong - Class Aliases

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine-User-Guide#210]
**Description of the problem**
The example given for giving an add-on a [Class Alias](https://docs.expressionengine.com/latest/development/addon-setup-php-file.html#aliases) appears to be wrong.

The text suggests that the alias example given will create the alias `EllisLab\ExpressionEngine\Model\Channel\ChannelEntry` but the example contains the text 
```
'aliases' => [
  'ExpressionEngine\Model\Channel\ChannelEntry',
],
```
Presumably the example text should be 
```
'aliases' => [
  'EllisLab\ExpressionEngine\Model\Channel\ChannelEntry',
],
```
**Error Messages**
n/a

**Additional context**
n/a

**Comment by intoeetive** [comment]
@jcogs-design that is not wrong. `EllisLab` prefix will be added automagically when the array is not associative.

**Comment by jcogs-design** [comment]
Ahah - well perhaps the language used to describe this could be made clearer...?

**Comment by intoeetive** [comment]
Please feel free to create a pull request with the proposed text change :)
