### ISSUE TITLE
Duplicate search link names

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine-User-Guide#25]
**Description of the problem**
When searching for "global variables" you get three identical results called "Global Variables", two of the links are for forum variables and the other for normal template variables.

A bit confusing! 

**Additional context**
Suggest renaming the titles used for the search links, say "Template Global variables" and "Forum Global Variables", anything to avoid confusion.

There may be other duplicate titles but I haven't found any so far.

**Comment by blue-dreamer** [comment]
Found another duplicate, search for "file" you get identical link names which go to different pages.

**Comment by Jordan-Ellis** [comment]
Thanks, @blue-dreamer. We'll get that fixed.

**Comment by blue-dreamer** [comment]
Hi Jordan

Good stuff, keep up the good work!

Rob
