### ISSUE TITLE
Certain codeblock syntax/content combo breaks TOC generator

### ISSUE THREAD

**Issue by ricklecoat** [ExpressionEngine/ExpressionEngine-User-Guide#28]
**Description of the problem**
Backtick-delineated codeblock containing #-style markdown headers interferes with/breaks automated (H2 and H3) TOC generation for the page.

**Error Messages**
None, to my knowledge.

**Additional context**
Whilst working on some new content for the documentation (a unified guide to using Markdown), I noticed that the automatic in-page TOC generator had stopped adding items for headings below a certain point of the page (ie. only the first few H2 and H3 headings were being turned into in-page TOC items). I traced the problem to a particular codeblock that I had added. This codeblock was delineated by the **triple-backtick syntax**, and was used to demonstrate Markdown headers that use the #, ##, ### (etc) system. Eg:

```
# This is an H1
## This is an H2
### This is an H3
(etc)
```

Other code blocks on the same page that also used the triple-backtick system did **not** cause this problem, and when I changed the offending code block to one delimited by indentation rather than backticks, the problem disappeared — even though the contents of the code block was the same. The issue therefore seems to be only caused by a **combination** of the triple-backtick syntax, and having the `# This Is A Header` syntax inside. 

I'll provide some examples here for further clarity _(apologies for the '[3 backticks here]' faux-syntax, but I couldn't figure any other way to show code block delineation **within** a code block)_. So, this is fine:

```
[3 backticks here]
This is an H1
=============

This is an H2
-------------
[3 backticks here]
```

…and this is fine (ie. indented = codeblock):

```
    # This is an H1
    ## This is an H2
    ### This is an H3
    (etc)
```

…but this combination of the above seems to break the TOC generator:

```
[3 backticks here]
# This is an H1
## This is an H2
### This is an H3
(etc)
[3 backticks here]
```

Conceivably other combinations may also cause problems, but this is the one I ran up against.

**Comment by Jordan-Ellis** [comment]
Hi Rick, thanks for the in-depth explanation. Currently, the TOC generation uses regex to get all page headings (which doesn't account for the backtick syntax). For now, I would recommend using indented code blocks until we find a proper solution.
