### ISSUE TITLE
Style Guide 404ing

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine-User-Guide#383]
**Description of the problem**
Style guide links are 404ing. 

Coming from this page in the documentation: https://docs.expressionengine.com/latest/development/services/table.html#cptable-service

Attempting to click on the `style-guide for tables` for link leads to: https://expressionengine.com/style-guide/c/listings#tables-common

This link does not exist.

**Comment by robsonsobral** [comment]
@Yulyaswan, do you know SassDOC? Are you interested to use it to create a style guide?

**Comment by bryannielsen** [comment]
It looks like that link has been removed from the current version of the docs so I'm going to close this issue for now.
