### ISSUE TITLE
Embed media fieldtype

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine-User-Guide#408]
Currently, there's sole responsibility to developers to came with a solution to embed media within entries.

Most of the time, everybody uses plugins for every different provider, which get outdated and demand extra attention from developers or site maintainers. We could have an Embed Media field type!

The [list of supported embeds on WP](https://wordpress.org/support/article/embeds/#okay-so-what-sites-can-i-embed-from) could be our starting point:

- [Amazon Kindle instant previews](http://amazon.com/)
- [Animoto](http://animoto.com/)
- [Cloudup](http://cloudup.com/)
- [Crowdsignal](https://crowdsignal.com/)
- [DailyMotion](http://www.dailymotion.com/)
- [Facebook](https://www.facebook.com/)
- [Flickr](http://www.flickr.com/)
- [Giphy](http://giphy.com/)
- [Imgur](http://imgur.com/)
- [Instagram](http://instagram.com/)
- [Issuu](http://issuu.com/)
- [Kickstarter](http://www.kickstarter.com/)
- [Meetup.com](http://meetup.com/)
- [Mixcloud](http://mixcloud.com/)
- [Photobucket](http://photobucket.com/)
- [Reddit](http://reddit.com/)
- [ReverbNation](http://reverbnation.com/)
- [Scribd](http://www.scribd.com/)
- [SlideShare](http://www.slideshare.net/)
- [SmugMug](http://www.smugmug.com/)
- [SoundCloud](http://soundcloud.com/)
- [Speaker Deck](http://speakerdeck.com/)
- [Spotify](http://www.spotify.com/)
- [TED](http://www.ted.com/)
- [TikTok](https://www.tiktok.com/en)
- [Tumblr](http://www.tumblr.com/)
- [Twitter](http://twitter.com/)
- [VideoPress](http://videopress.com/)
- [Vimeo](http://vimeo.com/)
- [WordPress plugin directory](https://wordpress.org/plugins-wp/)
- [WordPress.tv](http://wordpress.tv/)
- [YouTube](http://www.youtube.com/)

**Comment by bryannielsen** [comment]
This was moved to a discussion on the main repository https://github.com/ExpressionEngine/ExpressionEngine/discussions/2960
