### ISSUE TITLE
EE7 Docs: A few small typos

### ISSUE THREAD

**Issue by tboelskifte** [ExpressionEngine/ExpressionEngine-User-Guide#481]
**Description of the problem**
These are no big deal, but to keep the high professionalism of the docs, I thought I'd mention them.

When upgrading to EE7 the CP will display the **File Manager is set to Compatibility Mode** info-box. Here we're missing a _"the"_ and a _"with"_ as shown in this screenshot:

https://thomasb.dev/screenshots/eedocs-v7-typo1.jpg

And in the **Compatibility Note** under **Settings** &rarr; **Content & Design** &rarr; **File Manager** we have a _"then"_ that should be a _"than",_ as shown in this screenshot:

https://thomasb.dev/screenshots/eedocs-v7-typo2.jpg

**Comment by bryannielsen** [comment]
@tboelskifte thanks for taking the time to report these, unfortunately I can no longer see the screenshots you took I can't find the first typo you've referenced.  The second one I believe is here https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/blob/7.dev/docs/control-panel/file-manager/file-manager.md?plain=1#L189

> you can run the Update File Usage (found in Tools-> Utilities-> Update File Usage) and then disable Compatibility Mode

And I believe `then` is the correct choice.  Please feel free to reopen if you have more information or disagree!
