### ISSUE TITLE
404 Error from Edit This Page

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine-User-Guide#695]
I'm seeing a 404 error when clicking the "Edit This Page" link from here:
https://docs.expressionengine.com/latest/add-ons/pro-search/tags.html

Looks like it's pointing to the v6 docs instead of v7.

**Comment by TomJaeger** [comment]
Hi Oliver,

Thanks for pointing this out.  The link has been updated!
