### ISSUE TITLE
Standard Global Variables logged_in_location no longer exists in EE5

### ISSUE THREAD

**Issue by Yvan256** [ExpressionEngine/ExpressionEngine-User-Guide#7]
https://docs.expressionengine.com/latest/templates/globals/single_variables.html#logged-in-location

I was trying to use the location field of members to store a member-related variable but EE5 no longer interprets the {logged_in_location} tag, there is no "location" field anywhere in the control panel "Personal Settings" page of members (and anywhere that I can find) and the database table "exp_members" does not have a "location" column anymore.

I did a clean install of ExpressionEngine 5 (not an upgrade, no data was imported), if that helps.

**Comment by kevincupp** [comment]
Many of the default member fields were removed in favor of adding just the ones you want via custom member fields. You should be able to create a field for location and use that.

**Comment by kevincupp** [comment]
We'll make sure to update the docs though!

**Comment by Yvan256** [comment]
Thank you.
