### ISSUE TITLE
Revise upgrade instructions v2-v6

### ISSUE THREAD

**Issue by inoatech** [ExpressionEngine/ExpressionEngine-User-Guide#92]
**Description of the problem**
As of today, the new EE6 docs haven't been updated to reflect the new update process from EE2.

They still state:
```
Important: If you are upgrading from ExpressionEngine 2, you must first upgrade to ExpressionEngine 3 using version 3 files and instructions. Once you have completed that update, you may return to this page and upgrade to the latest version. Please visit Upgrading from ExpressionEngine 2.
```

**Comment by ops-andy** [comment]
We also need to add the Post Upgrade Debug Utility to the upgrade instructions.

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
