### ISSUE TITLE
"Add Row" button is not worked in the grid-input of CP/Table without adding "fieldset-faux" as parent

### ISSUE THREAD

**Issue by Bhavin9898** [ExpressionEngine/ExpressionEngine-User-Guide#94]
**Description of the problem**
In the document, there is the missing thing is that **"fieldset-faux"** is needed as a parent of the created grid structure to create the grid input in the CP/Table service.

Document: https://docs.expressionengine.com/latest/development/services/table.html#using-as-a-grid-input

**Bug**
If we not add the **"fieldset-faux"** then the "Add Row" button is not worked.

**Suggestion**
We can add this thing in the document as the current situation. EE team can add this class for this service via the code in the next version.

**Comment by ops-andy** [comment]
Thanks for pointing this out. We're going to investigate this one. If it's a bug, it probably needs to be fixed instead of just documented. If it's expected, then yes, we need to update the docs.

**Comment by ops-andy** [comment]
@Bhavin9898 ok. Yuri confirmed that this is expected so we indeed just need to update the docs. I see you made the necessary changes in your fork of the docs. Do you want to open a PR from your fork into the repo and then I'll add some more details as well.
thanks!

**Comment by Bhavin9898** [comment]
Hello @ops-andy ,

Thanks for the comment and confirmation.

Yes, I want to open a PR from my fork into repo.

Let me do it.

**Comment by Bhavin9898** [comment]
Hello @ops-andy ,

I have just opened the pull request for it.

Let me know if you want anything from my side.

Thanks

**Comment by ops-andy** [comment]
awesome. thanks
